import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Button } from '../../Button/Button';
declare const _default: ComponentMeta<typeof Button>;
export default _default;
export declare const Props: any;
export declare const Emphasis: ComponentStory<typeof Button>;
export declare const PositiveNegative: ComponentStory<typeof Button>;
export declare const Circular: ComponentStory<typeof Button>;
export declare const Color: ComponentStory<typeof Button>;
export declare const Size: ComponentStory<typeof Button>;
export declare const Compact: ComponentStory<typeof Button>;
